name = "probly"
version = "0.0.2"
description = "Probabilistic functional programming in Gleam"
licenses = ["MIT"]
repository = { type = "github", user = "raquentin", repo = "probly" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
